openapi: 3.0.3
info:
  title: Time Logger API
  description: |
    API для сервиса записи времени.
    
    Сервис записывает текущее время в базу данных каждую секунду и предоставляет
    endpoint для получения всех записей в хронологическом порядке.
  version: 1.0.0

servers:
  - url: http://localhost:8080

tags:
  - name: TimeRecords
    description: Операции с записями времени

paths:
  /api/times:
    get:
      tags:
        - TimeRecords
      operationId: getAllTimeRecords
      summary: Получить записи времени
      description: |
        Возвращает страницу записей времени в хронологическом порядке.
      parameters:
        - name: page
          in: query
          description: Номер страницы (начиная с 0)
          required: false
          schema:
            type: integer
            default: 0
            minimum: 0
        - name: size
          in: query
          description: Количество записей на странице
          required: false
          schema:
            type: integer
            default: 20
            minimum: 1
            maximum: 1000
      responses:
        '200':
          description: Срез записей времени (без COUNT для оптимизации)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SliceTimeRecordResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'

  /api/times/count:
    get:
      tags:
        - TimeRecords
      operationId: getTimeRecordsCount
      summary: Получить количество записей
      description: Возвращает общее количество записей времени в базе данных.
      responses:
        '200':
          description: Количество записей
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'

components:
  schemas:
    TimeRecordResponse:
      type: object
      description: Запись времени из базы данных
      properties:
        id:
          type: integer
          format: int64
          description: Уникальный идентификатор записи
          example: 1
        recordedAt:
          type: string
          format: date-time
          description: Временная метка записи
          example: "2024-01-17T12:00:00"
      required:
        - id
        - recordedAt

    SliceTimeRecordResponse:
      type: object
      description: |
        Срез записей времени с метаданными пагинации.
        Использует Slice вместо Page для оптимизации производительности — 
        не выполняется COUNT(*) запрос, что критично при миллионах записей.
      properties:
        content:
          type: array
          description: Список записей на текущей странице
          items:
            $ref: '#/components/schemas/TimeRecordResponse'
        page:
          type: integer
          description: Текущий номер страницы (начиная с 0)
          example: 0
        size:
          type: integer
          description: Размер страницы
          example: 20
        numberOfElements:
          type: integer
          description: Количество элементов на текущей странице
          example: 20
        first:
          type: boolean
          description: Является ли текущая страница первой
          example: true
        last:
          type: boolean
          description: Является ли текущая страница последней
          example: false
        hasNext:
          type: boolean
          description: Есть ли следующая страница
          example: true
        hasPrevious:
          type: boolean
          description: Есть ли предыдущая страница
          example: false
      required:
        - content
        - page
        - size
        - numberOfElements
        - first
        - last
        - hasNext
        - hasPrevious

    CountResponse:
      type: object
      description: Ответ с количеством записей
      properties:
        count:
          type: integer
          format: int64
          description: Общее количество записей
          example: 1000
      required:
        - count

    ErrorResponse:
      type: object
      description: Ответ об ошибке
      properties:
        code:
          type: string
          description: Код ошибки
          example: "DB_UNAVAILABLE"
        message:
          type: string
          description: Описание ошибки
          example: "База данных временно недоступна"
        timestamp:
          type: string
          format: date-time
          description: Время возникновения ошибки
          example: "2024-01-17T12:00:00"
      required:
        - code
        - message
        - timestamp

  responses:
    Unauthorized:
      description: Требуется авторизация
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            code: "UNAUTHORIZED"
            message: "Требуется авторизация"
            timestamp: "2024-01-17T12:00:00"

    ServiceUnavailable:
      description: Сервис временно недоступен
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            code: "DB_UNAVAILABLE"
            message: "База данных временно недоступна"
            timestamp: "2024-01-17T12:00:00"

  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: HTTP Basic Authentication

security:
  - basicAuth: []
